// <auto-generated />
namespace RentMyWrox.ApplicationDbMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Personalization : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Personalization));
        
        string IMigrationMetadata.Id
        {
            get { return "201512132006270_Personalization"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
